### ISSUE TITLE
Wrong serverUrl when bound to localhost

### ISSUE THREAD

**Issue by dachev** [swisspol/GCDWebServer#123]
`serverUrl` uses the primary IP even when bound to localhost. This will bite apps that rely on GCDWebServer and `serverUrl` to serve offline content as the reported value is `nil`:

`GCDWebServer started on port 8080 and reachable at (null)`

**Comment by swisspol** [comment]
Yes this is by design so the method returns nil if the server is not reachable (since it relies on  `GCDWebServerGetPrimaryIPAddress ()` - see https://github.com/swisspol/GCDWebServer/blob/master/GCDWebServer/Core/GCDWebServerFunctions.h#L66). If you are running your server only locally, then you know the URL is `localhost` or `127.0.0.1`.

**Comment by dachev** [comment]
Then the method name is misleading and semantically wrong because it does not return the server URL. Consider splitting this into two methods: `serverUrl` and `isReachable`.

**Comment by swisspol** [comment]
I should have phrased it better: it's not so much reachability, this method returns the server public URL based on the device IP address if available. You don't need this method if you run the server locally only as you already know what the URL is anyway.

Feel free to send in a PR if you want to suggest renaming this method maybe to `serverPublicURL` (and then the bonjour one accordingly to `serverBonjourURL`).
