### ISSUE TITLE
Not Working in Xcode 6.2 with Swift

### ISSUE THREAD

**Issue by jigzat** [swisspol/GCDWebServer#159]
it keeps insisting that contentType parameter is missing although I'm calling GCDWebServerDataResponse(text: "Hello")

**Comment by swisspol** [comment]
A content type parameter is indeed required to instantiate `GCDWebServerDataResponse`: see the corresponding header file.

**Comment by jigzat** [comment]
I'm sorry to bother you but it is not working either. I copy and paste the iOS Swift code example :

return GCDWebServerDataResponse(HTML:"<html><body><p>Hello World</p></body></html>")

and I get the same error.

If I do :

return GCDWebServerDataResponse(data: someData, contentType: aContentType))

I receive a "Cannot invoque 'init' with an argument list of type (data: @lvalue NSData, contentType:@lvalueNSString)"

**Comment by swisspol** [comment]
That example for Swift was written a while back so it's possible the language has changed and some other syntax is now required. I don't use Swift personally so I can't comment on this.

Your issue is unfortunately not a GCDWebServer problem though: it's a Swift language question. I would encourage you to ask the question on Stack Overflow instead. Sorry not to be able to help more.
