### ISSUE TITLE
connection does not seem to get closed when using asyncprocessBlock

### ISSUE THREAD

**Issue by wuftymerguftyguff** [swisspol/GCDWebServer#198]
I am trying to pass the AsyncProcessBlock into another object so that I can call it when a complex chain of async stuff completes.

GCD Webserver seems to send the main part of the response, but not close the connection, so the browser does not continue until I manually stop the web server, or the whole app with the web server.

log looks like this if using sync response

[DEBUG] Connection sent 122 bytes on socket 26
[DEBUG] Did close connection on socket 26
[VERBOSE] [127.0.0.1:80] 127.0.0.1:59226 200 "GET /c3FybDovL3d3dy5ncmMuY29tL3Nxcmw_bnV0PWUyS1FUS2Iybkk5VE96MV9NOUM0OXcmc2ZuPVIxSkQ" (465 | 122)
[DEBUG] Did disconnect

And like this when calling the continuation elsewhere in my application.

[DEBUG] Connection sent 122 bytes on socket 26

**Comment by swisspol** [comment]
GCDWebServer closes all its connections. If a connection remains open, that would be because you are somehow holding on it, which is likely due to not using the API as intended.

Be sure to read through the header documentations and https://github.com/swisspol/GCDWebServer#asynchronous-http-responses.
