### ISSUE TITLE
Can this library support ie8?

### ISSUE THREAD

**Issue by Vienta** [swisspol/GCDWebServer#215]
Hi 
Thank you for this excellent library！
But when I use it in ie8 brower, the file transfer failed.
I wonder if this lib can support IE8.

Regards
Vienta

**Comment by xiaoMingChina** [comment]
When i use your GCDWebUploader.bundle it is not support  to upload by ie8 or ie9.The phenomenon is that buttons no response.So i rewrite HTML and Javascript. But when i use ie8 or ie9 to upload musics(include MP3\WAV\AAC\M4A\FLAC\APE) there still has issues.When the Web Browser upload 100% and the files are already uploaded into the Client but it  would judge the state still is kParserState_Content.So it would failed finishing to parse multipart form data.And others Web Browser is OK.I think the reason is ie8 uses Adobe flash that the library makes a misjudgment when at end.Would you hava a good way to solve it?

**Comment by swisspol** [comment]
If I recall correctly, IE 8 and IE 9 were never supported. I have no idea what's going on nor how to fix it, sorry.

I just tested again:
- IE 11: Open dialog: PASS / Drag & drop: PASS
- IE 9: Open dialog: FAIL (button doesn't even work) / Drag & drop: FAIL (not recognized)
- IE 8: Open dialog: FAIL (button doesn't even work) / Drag & drop: FAIL (not recognized)
