### ISSUE TITLE
HTTPS Support

### ISSUE THREAD

**Issue by gavinwilliams** [swisspol/GCDWebServer#222]
It would be awesome to support HTTPS with GCDWebServer. Google Chrome is now restricting certain features (WebRTC) to work only over HTTPS in the interest of security. I.e. access to the web cam and microphone through getUserMedia.

http://www.tokbox.com/blog/the-impact-of-googles-new-chrome-security-policy-on-webrtc/

You can probably host your front end over a seperate server over HTTPS, but you can't make Ajax calls over HTTP to GCDWebServer. You also can't upload large files over a HTTP Proxy easily like this.

Has anybody started on HTTPS support? If so, how far have you gotten?

We obviously want it and are happy to contribute, implement and share this feature. Would be good to know what the demand is.

**Comment by swisspol** [comment]
This is going to be very hard to implement because GCDWebServer is entirely built around the GCD APIs to read / write asynchronously from sockets while the SecureTransport APIs, which are required to implement TLS, are not designed to work like this at all. So either GCDWebServer internals need to be partially rewritten, which is not going to happen, or some sort of adapter to make SecureTransport APIs work asynchronously on top of GCD need to be written, which is far from trivial due to the edge cases.
