### ISSUE TITLE
Version 3.3 seems causing  dyld_fatal_error with Xcode 7.2 with OSX 10.11.2

### ISSUE THREAD

**Issue by zwang** [swisspol/GCDWebServer#252]
I am using this library https://github.com/omcljs/ambly which depends on GCDWebServer. It seems version 3.3 will cause dyld_fatal_error when app crash during start up on device on debugging mode. While running on Simulator, it will cause a break point pause but not crashing if I turn 'enableAddressSanitizer' on. After I specify to always using version 3.2.7 in Carthage file, everything works well. Just FYI. 

My project is using Swift 2.1.1 just in case this makes a difference

**Comment by swisspol** [comment]
What's in the Xcode log?

**Comment by zwang** [comment]
In the log it shows:

'dyld: Library not loaded: @rpath/libclang_rt.asan_ios_dynamic.dylib
  Referenced from: /private/var/mobile/Containers/Bundle/Application/6F08A5EF-401A-4EC6-B2DE-FFF8E2EBEA9F/Plato.app/Frameworks/GCDWebServers.framework/GCDWebServers
  Reason: image not found'

Screenshot attached:
![screen_shot_2016-01-04_at_9_40_30_pm](https://cloud.githubusercontent.com/assets/1171212/12108395/39b68ca8-b32c-11e5-8dc7-d963375c553a.png)

Thanks!

**Comment by swisspol** [comment]
That's a most puzzling issue. Nobody else has ever reported something like this so there must be something very unique with your Xcode project configuration.

There's nothing that can be done on my side since there's no repro steps. You could try manually checking out GCDWebServer at version 3.2.7 and then walk the Git history commit by commit until you find the one that triggers the bug. There were few commits and I don't see anything suspicious.

I'm suspecting an Xcode configuration problem in your app which was just exposed by a recent change in this project.

**Comment by zwang** [comment]
I see. If nobody else has the issue, it's fine. I am happy just staying with 3.2.7 for now.I only use Ambly for debugging purpose. So no biggy.

Thanks for the library.

**Comment by aral** [comment]
I’m getting exactly the same error with 3.3 and Carthage.

**Comment by briancroom** [comment]
Dug into this a little bit... found that GCDWebServer 3.3 has the Address Sanitizer enabled in the shared schemes for the frameworks. I expect that Xcode isn't setting up the dynamic library required to make the address sanitizer work for the app targets because it's just looking at whether ASAN is enabled in the app, not in any embedded frameworks.

**Comment by aral** [comment]
Cool, thank you, @briancroom — will take a look at that :)

**Comment by swisspol** [comment]
Oh, that's interesting. I'll turn this off them.

**Comment by ratkins** [comment]
We're having this same issue. Is this turned off in https://github.com/swisspol/GCDWebServer/commit/a4c61bd07190171006ae213b64629b4b6c6a5db0 (3.3.2)? I couldn't find this in any of the commits.

**Comment by swisspol** [comment]
No I forgot to turn this off, I just fixed it.

The version that I released a few days ago was 3.3.1, not 3.3.2.
