### ISSUE TITLE
IPv6 only network

### ISSUE THREAD

**Issue by haphanquang** [swisspol/GCDWebServer#348]
Hi.
I tested and GCDWebServer working fine with ipv4 network but cannot use it for upload file in ipv6 only network.

And App Store also rejected my build.

> Thank you for your resubmission. After further view we discovered one or more bugs in your app when reviewed on iPad running iOS 11.1 on Wi-Fi connected to an IPv6 network.
> 
> Specifically, we found that we were unable to connect to the server address on our desktop provided by your app

I use this property to guide user to use their pc...

` @property(nonatomic, readonly, nullable) NSURL* serverURL; `

Please support me.

**Comment by duannl** [comment]
Does anyone know how to fix this issue? Thanks.

**Comment by sheff1422** [comment]
@swisspol  any updates to this?

**Comment by sheff1422** [comment]
Anyone who will experience this issue please try to use property -> .bonjourServerURL instead. Or just localhost:port

**Comment by swisspol** [comment]
“serverURL” returns an IPv4 address:
https://github.com/swisspol/GCDWebServer/blob/a5548938448c7a197996609c4b7d6592117b9d22/GCDWebServer/Core/GCDWebServer.m

If you are on an IPv6 only network, you need to show the user an IPv6 address, otherwise they won’t be able to connect if they specify and IPv4 address. You can simply make your own version of “serverURL”.
