### ISSUE TITLE
Can't access via Google Chrome/Cast products

### ISSUE THREAD

**Issue by jkichline** [swisspol/GCDWebServer#430]
I know that you don't support HTTPS in GCDWebServer, but we are needing a solution unfortunately. Google is now preventing access to non-secure websites and that also means those on the local network. Is there some kind of solution that can be created to handle this or should we tell 56% of users they are SOL?

**Comment by swisspol** [comment]
You would need to fork the project and add HTTPS support yourself. Then you would need a self signed certificate which the chrome cast may reject anyway.

However I would check first that the issue still happens when using a local IP address: it seems very surprising that the chrome cast would require https for local IP addresses..
